plugins {
    id 'java'
    id "io.qameta.allure" version "2.20.1"  // Обновлено до последней версии
    id "org.gradle.test-retry" version "1.5.3"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
    autoconfigure = true
}

dependencies {
    implementation 'io.qameta.allure:allure-testng:2.22.0' // Обновлено до последней версии
    implementation 'org.testng:testng:7.9.0'               // Обновлено до последней версии
    testImplementation 'junit:junit:4.13.2'                 // Обновлено до последней версии
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0' // Обновлено до последней версии
    runtimeOnly 'org.aspectj:aspectjweaver:1.9.20'          // Обновлено до последней версии
    implementation 'io.rest-assured:rest-assured:5.4.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'org.seleniumhq.selenium:selenium-java:4.13.0' // Обновлено до последней версии
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.2' // Обновлено до последней версии
    implementation 'com.github.javafaker:javafaker:1.0.2'
    implementation 'com.squareup.okhttp3:okhttp:4.11.0' // Обновлено до последней версии
    implementation 'org.seleniumhq.selenium:selenium-chromium-driver:4.13.0' // Обновлено до последней версии
    implementation 'org.projectlombok:lombok:1.18.30'
}

test {
    useTestNG()
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat "full"
    }
}

task SmokeTestE2e(type: Test) {
    useTestNG {
        suites 'src/test/resources/testngE2eSmoke.xml'
    }
    systemProperty 'allure.results.directory', 'build/allure-results'
}

task ApiTest(type: Test) {
    useTestNG {
        suites 'src/test/resources/testngApi.xml'
    }
    systemProperty 'allure.results.directory', 'build/allure-results'
}

task ProbeTest(type: Test) {
    useTestNG {
        suites 'src/test/resources/testngE2eSmokeTesting.xml'
    }
    systemProperty 'allure.results.directory', 'build/allure-results'
}
